### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by xdcabc** [H0uzC/fkrjgzhu#2]
checking whether mkfifo rejects trailing slashes... yes
checking whether mknod can create fifo without root privileges... configure: error: in `/root/lede/build_dir/host/tar-1.32':
configure: error: you should not run configure as root (set FORCE_UNSAFE_CONFIGURE=1 in environment to bypass this check)
See `config.log' for more details
make[3]: *** [Makefile:32: /root/lede/build_dir/host/tar-1.32/.configured] Error 1
make[3]: Leaving directory '/root/lede/tools/tar'
time: tools/tar/compile#8.69#4.01#15.11
make[2]: *** [tools/Makefile:165: tools/tar/compile] Error 2
make[2]: Leaving directory '/root/lede'
make[1]: *** [tools/Makefile:161: /root/lede/staging_dir/host/stamp/.tools_compile_yyyyyynnyyyynyyyyynyynnyyyynyyyyyyyyyyyyyyyyynynnyyyynynyyyy] Error 2
make[1]: Leaving directory '/root/lede'
make: *** [/root/lede/include/toplevel.mk:224: world] Error 2
这报错是什么意思呢？

**Comment by H0uzC** [comment]
你用了`root`用户来`git clone`或`make menuconfig`了
在`bulid`的**第二步和第三步之间**已经写明不要使用`root`用户和`sudo`命令
